AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an RHEL EC2 instance with Git, Jenkins, and Docker pre-installed.

Parameters:
  UAI:
    Type: String
    Description: Name of the application
    MaxLength: 10
  AppName:
    Type: String
    Description: Name of the application
    MaxLength: 10
  AppInstance:
    Type: String
    Description: Name of the application
    MaxLength: 10
  Env:
    Type: String
    Description: Environment of the application
    AllowedValues:
      - dev
      - qa
      - stg
      - prd
  ImageId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
  RootVolSize:
    Type: Number
    Description: Size of the disk (GB)
    Default: 50 
  EC2InstanceProfile:
    Type: String
    Description: Instance profile for server (only name no ARN or Path)
    Default: ''
  EC2Type:
    Type: String
    Description: Type of Instance
    AllowedValues:
      - t3.medium
      - t2.large
      - t3.large
      - m5.large
      #keep as many as you want
     

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      KeyName: !Ref KeyName
      #ImageId: ami-0a887e401f7654935 # Replace with the RHEL AMI ID for your region
      ImageId: !Ref ImageId
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: !Ref RootVolSize
            VolumeType: gp3
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          yum update -y
          # Install Git
          yum install -y git
          # Install Docker
          yum install -y docker
          systemctl start docker
          systemctl enable docker
          # Install Jenkins
          wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo
          rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key
          yum install -y jenkins java-11-openjdk
          systemctl start jenkins
          systemctl enable jenkins
      Tags:
        - Key: Name
          Value: RHEL-EC2-Jenkins-Docker-Git
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH, HTTP, and Jenkins access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0

Outputs:
  InstanceId:
    Description: The Instance ID of the newly created EC2 instance
    Value: !Ref EC2Instance
  PublicIP:
    Description: Public IP address of the newly created EC2 instance
    Value: !GetAtt EC2Instance.PublicIp
